stages:
- build
- test

build:
  stage: build
  image: golang:1.23.4-alpine3.21
  script:
    - "go mod tidy"
    - "go build -o dist/ts-api"
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days
    paths:
      - "dist/"
