global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel_metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets: [ 'jaeger:8889' ]
